name: rck_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1W

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.2
  http: ^0.12.0+2
  meta: ^1.3.0
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
